<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ddf</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C#</string>
	<key>name</key>
	<string>DDF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hash</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((module)\s+([\w.]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.module.identifier.ddf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.ddf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module.ddf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Modules</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.module.end.ddf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.ddf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((namespace)\s+([\w.]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.namespace.identifier.ddf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.namespace.ddf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.ddf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Namespaces</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.namespace.end.ddf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.namespace.ddf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.ddf</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Imports</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.hash.end.ddf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.import.ddf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringliterals</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[([A-Z]\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.ddf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Attributes on fields/classes</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\(</string>
							<key>comment</key>
							<string>Attributes can have parameters</string>
							<key>end</key>
							<string>\)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\b([A-Z]\w+)\b=\s*</string>
									<key>comment</key>
									<string>The parameters can be single literals, or named</string>
									<key>end</key>
									<string>(?=\)|,)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#literals</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#literals</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>builtInTypes</key>
		<dict>
			<key>match</key>
			<string>\b(bool|s8|u8|s16|u16|s32|int|u32|uint|u64|s64|float|f32|double|f64|vec2|vec3|string|class|struct|enum|nativestruct)\b</string>
			<key>name</key>
			<string>storage.type.ddf</string>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(?=\w?[\w\s]*(?:class|struct|enum|nativestruct)\s+\w+)</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.class.end.ddf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.ddf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storagemods</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.ddf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.ddf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(class|struct|nativestruct|enum)\s+(\w+)</string>
					<key>name</key>
					<string>meta.class.identifier.ddf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>comment</key>
					<string>Handle base types</string>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.ddf</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*,?([A-Za-z_]\w*)\b</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.class.begin.ddf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Handle the actual class/struct/enum body</string>
					<key>end</key>
					<string>(?=\})</string>
					<key>name</key>
					<string>meta.class.body.ddf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storagemods</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fields</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ddf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.ddf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.ddf</string>
				</dict>
			</array>
		</dict>
		<key>fields</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(?:\b(override)\b\s+)?(?=\b[A-Za-z]\w+\s+[A-Za-z]\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.ddf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#builtInTypes</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?:\b([A-Za-z]\w+)\s+)?\b([A-Za-z]\w+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.ddf</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.ddf</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>If the built in types don't consume any tokens, assume it is a user type</string>
							<key>end</key>
							<string>(?=;|=)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>=</string>
							<key>comment</key>
							<string>Assignment</string>
							<key>end</key>
							<string>(?=;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#literals</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>hash</key>
		<dict>
			<key>begin</key>
			<string>^\s*((hash)\b\s+([\w.]+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.hash.identifier.ddf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.hash.ddf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.raw.ddf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.hash.end.ddf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.hash.ddf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringliterals</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Language literals</string>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.ddf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Numeric literals</string>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
					<key>name</key>
					<string>constant.numeric.ddf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stringliterals</string>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.include.ddf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.other.ddf</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#\s*(include)\b\s*(\S*)</string>
				</dict>
			</array>
		</dict>
		<key>storagemods</key>
		<dict>
			<key>match</key>
			<string>\b(public|protected|private|static|abstract|virtual|override|meta)\b</string>
			<key>name</key>
			<string>storage.modifier.ddf</string>
		</dict>
		<key>stringliterals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.ddf</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Strings</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.ddf</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ddf</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.ddf</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ddf</string>
	<key>uuid</key>
	<string>d9969a89-c31b-428f-8cd8-d7db80d9745f</string>
</dict>
</plist>
